// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using database;

#nullable disable

namespace database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260414124502_sosidebil")]
    partial class sosidebil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("domains.domains.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_at");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("sessionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("domains.domains.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("domains.domains.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_at");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_question_index");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("QuantityCompletedQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_completed_questions");

                    b.Property<int>("QuantityQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_questions");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("progresses");
                });

            modelBuilder.Entity("domains.domains.Player", b =>
                {
                    b.HasOne("domains.domains.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("domains.domains.Progress", b =>
                {
                    b.HasOne("domains.domains.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domains.domains.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("domains.domains.PlayerQuizResult", "QuizResult", b1 =>
                        {
                            b1.Property<int>("ProgressId")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsFinished")
                                .HasColumnType("boolean")
                                .HasAnnotation("Relational:JsonPropertyName", "isFinished");

                            b1.Property<int>("QuantityCorrectAnswers")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "quantityCorrectAnswers");

                            b1.Property<int>("QuizId")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "quizId");

                            b1.HasKey("ProgressId");

                            b1.ToTable("progresses");

                            b1.ToJson("quiz_result");

                            b1.WithOwner()
                                .HasForeignKey("ProgressId");

                            b1.OwnsMany("domains.domains.QuestionResult", "Questions", b2 =>
                                {
                                    b2.Property<int>("PlayerQuizResultProgressId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Complexity")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "complexity");

                                    b2.Property<int>("Index")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "Index");

                                    b2.Property<string>("QuestionId")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "questionId");

                                    b2.Property<int>("QuestionIndex")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "questionIndex");

                                    b2.Property<string>("QuestionText")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "questionText");

                                    b2.HasKey("PlayerQuizResultProgressId", "__synthesizedOrdinal");

                                    b2.ToTable("progresses");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "questions");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerQuizResultProgressId");

                                    b2.OwnsMany("domains.domains.AnswerResult", "Answers", b3 =>
                                        {
                                            b3.Property<int>("QuestionResultPlayerQuizResultProgressId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("QuestionResult__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("AnswerId")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasAnnotation("Relational:JsonPropertyName", "answerId");

                                            b3.Property<int>("AnswerIndex")
                                                .HasColumnType("integer")
                                                .HasAnnotation("Relational:JsonPropertyName", "answerIndex");

                                            b3.Property<string>("AnswerText")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasAnnotation("Relational:JsonPropertyName", "answerText");

                                            b3.Property<bool>("IsCorrect")
                                                .HasColumnType("boolean")
                                                .HasAnnotation("Relational:JsonPropertyName", "isCorrect");

                                            b3.HasKey("QuestionResultPlayerQuizResultProgressId", "QuestionResult__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("progresses");

                                            b3.HasAnnotation("Relational:JsonPropertyName", "answers");

                                            b3.WithOwner()
                                                .HasForeignKey("QuestionResultPlayerQuizResultProgressId", "QuestionResult__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Answers");
                                });

                            b1.Navigation("Questions");
                        });

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("QuizResult")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
